name: CI/CD

on:
  push:
    tags:
      - '*'

jobs:
  build-and-publish:
    name: Build and Publish
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.100

      - name: Build and Publish VKDialogFileMergerForm (Windows Forms)
        if: startsWith(github.ref, 'refs/tags/')
        run: dotnet publish VKDialogFileMergerForm/VKDialogFileMergerForm.csproj -c Release -r win-x64 --output ./VKDialogFileMergerForm/bin/Release/net6.0-windows/win-x64/publish

      - name: Build and Publish VKDialogFileMerger (CLI Windows)
        run: dotnet publish VKDialogFileMerger/VKDialogFileMerger.csproj -c Release -r win-x64 --output ./VKDialogFileMerger/bin/Release/net6.0/win-x64/publish

      - name: Build and Publish VKDialogFileMerger (CLI Linux)
        run: dotnet publish VKDialogFileMerger/VKDialogFileMerger.csproj -c Release -r linux-x64 --output ./VKDialogFileMerger/bin/Release/net6.0/linux-x64/publish

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
