name: CI/CD

on:
  push:
    tags:
      - '*'

jobs:
  build-and-publish:
    name: Build and Publish
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3.2.0
        with:
          dotnet-version: 6.0.100

      - name: Install 7-Zip
        run: |
          # Download 7-Zip
          Invoke-WebRequest -Uri 'https://www.7-zip.org/a/7z1900-x64.exe' -OutFile '7z.exe'

          # Install 7-Zip silently
          Start-Process -Wait -FilePath '7z.exe' -ArgumentList '/S'

      - name: Build and Publish VKDialogFileMergerForm (Windows Forms)
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          dotnet publish ./VKDialogFileMergerForm/VKDialogFileMergerForm.csproj -c Release -r win-x64 -p:PublishSingleFile=true --self-contained false --output ./VKDialogFileMergerForm/bin/Release/net6.0-windows/win-x64/publish
          cd ./VKDialogFileMergerForm/bin/Release/net6.0-windows/win-x64/publish
          7z a -r VKDialogFileMergerForm.zip .

      - name: Build and Publish VKDialogFileMerger (CLI Windows)
        run: |
          dotnet publish ./VKDialogFileMerger.csproj -c Release -r win-x64 -p:PublishSingleFile=true --self-contained false --output ./VKDialogFileMerger/bin/Release/net6.0/win-x64/publish
          cd ./VKDialogFileMerger/bin/Release/net6.0/win-x64/publish
          7z a -r VKDialogFileMerger-Windows.zip .

      - name: Build and Publish VKDialogFileMerger (CLI Linux)
        run: |
          dotnet publish ./VKDialogFileMerger.csproj -c Release -r linux-x64 -p:PublishSingleFile=true --self-contained false --output ./VKDialogFileMerger/bin/Release/net6.0/linux-x64/publish
          cd ./VKDialogFileMerger/bin/Release/net6.0/linux-x64/publish
          7z a -r VKDialogFileMerger-Linux.zip .
          
      - name: Generate Release Notes
        run: |
          current_tag=${GITHUB_REF#refs/tags/}
          previous_tag=$(git describe --tags --abbrev=0 $current_tag^)
          release_notes=$(git log $previous_tag..$current_tag --pretty=format:'- %s')
          echo "release_notes=$release_notes" >> $GITHUB_ENV

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            VKDialogFileMergerForm/bin/Release/net6.0-windows/win-x64/publish/VKDialogFileMergerForm.zip
            VKDialogFileMerger/bin/Release/net6.0/win-x64/publish/VKDialogFileMerger-Windows.zip
            VKDialogFileMerger/bin/Release/net6.0/linux-x64/publish/VKDialogFileMerger-Linux.zip
          body: ${{ env.release_notes }}
